In [2]:
import numpy as np
numbers=np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


In [ ]:
#Suppose we want to add 10 to every value
#We need a loop
numbers=[10,20,30,40,50,60]
result=[]

for number in numbers:
    result.append(number+10)
print(result)

[20, 30, 40, 50, 60, 70]


In [5]:
#Using numpy
#Numpy allows us to perform the operation directly
import numpy as np
numbers=np.array([10,20,30,40,50,60])
result=numbers+10
print(result)

[20 30 40 50 60 70]


In [10]:
#Numpy Array Arithmetic
import numpy as np
numbers=np.array([10,20,30,40,50])

print(numbers+5)
print(numbers-5)
print(numbers*5)
print(numbers/5)

[15 25 35 45 55]
[ 5 15 25 35 45]
[ 50 100 150 200 250]
[ 2.  4.  6.  8. 10.]


In [11]:
#Creating Numpy Arrays:
#np.array(object)
numbers=np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [12]:
#Creating a 1D array
numbers=np.array([10,20,30,40,50])
print(numbers.ndim)

1


In [14]:
#Creating a 2D array
numbers=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(numbers)
print(numbers.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2


In [15]:
#Creating a 3D array
numbers=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]

])
print(numbers)
print(numbers.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [16]:
numbers=np.array([10,20,30,40,50])
print(numbers.shape)

(5,)


In [ ]:
numbers=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(numbers.shape) # 3-rows and 3-columns

(3, 3)


In [ ]:
numbers=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]

])
print(numbers.shape)# 2-blocks,2-rows and 3-columns

(2, 2, 3)


In [27]:
#Array properties
#The four properties :

#Ndim=>returns the number of dimensions(axes) of a numpy array.
numbers=np.array([10,20,30,40,50])
print(numbers.ndim)

#Shape=>returns the size of the array along with dimension.
numbers=np.array([10,20,30,40,50])
print(numbers.shape)

#Size=>returns the total number of elements present in the array.
#example 1
numbers=np.array([
    [10,20,30],
    [40,50,60]
])
print(numbers.size)

#example 2
numbers=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]

])
print(numbers.size)

#Dtype=>tells us data type of the element stored in a numpy array.
numbers=np.array([10,20,30,40])
print(numbers.dtype)

numbers=np.array([11.5,14.5,40.5,66.6])
print(numbers.dtype)

numbers=np.array(["swarna","kirthana","swarupa","sahadev"])
print(numbers.dtype)



1
(5,)
6
12
int64
float64
<U8


In [28]:
#1D Array
array_1d=np.array([10,20,30,40,50])

print("---------------- 1D ARRAY -----------------")
print(array_1d)
print("Dimensions: ",array_1d.ndim)
print("Shape: ",array_1d.shape)
print("Size: ",array_1d.size)
print("Data Type: ",array_1d.dtype)

#2D Array
array_2d=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print("\n---------------- 2D ARRAY -----------------")
print(array_2d)
print("Dimensions: ",array_2d.ndim)
print("Shape: ",array_2d.shape)
print("Size: ",array_2d.size)
print("Data Type: ",array_2d.dtype)

#3D Array
array_3d=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]


])

print("\n---------------- 3D ARRAY -----------------")
print(array_3d)
print("Dimensions: ",array_3d.ndim)
print("Shape: ",array_3d.shape)
print("Size: ",array_3d.size)
print("Data Type: ",array_3d.dtype)


---------------- 1D ARRAY -----------------
[10 20 30 40 50]
Dimensions:  1
Shape:  (5,)
Size:  5
Data Type:  int64

---------------- 2D ARRAY -----------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimensions:  2
Shape:  (3, 3)
Size:  9
Data Type:  int64

---------------- 3D ARRAY -----------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimensions:  3
Shape:  (2, 2, 3)
Size:  12
Data Type:  int64
