In [ ]:
#np.array()=>A function is used to convert a python list or tuple into a numpy array.

import numpy as np
numbers=np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [2]:
marks=np.array([85,90,78,92,88])
print(marks)

[85 90 78 92 88]


In [3]:
students=np.array([
    [10,85],
    [102,90],
    [103,78]
])
print(students)

[[ 10  85]
 [102  90]
 [103  78]]


In [ ]:
#np.zeros()=>function creates an array where all columns are initialized with 0.

#1D zeros array
arr=np.zeros(5)
print(arr)
print("=" * 50)
#2D zeros array
arr=np.zeros((3,4))
print(arr)
print("=" * 50)
#3D zeros array
arr=np.zeros((2,3,4))
print(arr)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
atttendence=np.zeros((5,7))
print(atttendence)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#np.ones()=>Function creates an array wher every elemnet is initialized with 1.
#1D array
arr=np.ones(5)
print(arr)
print("=" * 50)
#2D array
arr2=np.ones((3,4))
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
#np.arange()=>function creates an array containing values within a specific range.
#np.arange(start,stop,step)

arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [15]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
employee_ids=np.arange(1001,1011)
print(employee_ids)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]


In [17]:
#np.linspace=>function creates a specified number of equally spaced values between a starting and ending value
#np.linspace(start,stop,num)
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
print(np.arange(0,10,2))
print(np.linspace(0,10,6))

[0 2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


In [21]:
#Indexing and Slicing
#Indexing=>used to access a specific element from an array using its position
#Positive indexing in a 1D Array
numbers=np.array([10,20,30,40,50])
print(numbers[0])
print(numbers[2])
print(numbers[3])
print(numbers[4])
print("=" * 50)
#Negative indexing=>starts from end of the array
numbers=np.array([10,20,30,40,50])
print(numbers[-1])
print(numbers[-2])
print(numbers[-3])
print(numbers[-4])

10
30
40
50
50
40
30
20


In [26]:
#Slicing in 1D array=> Array[start:stop]->stop index is not included
numbers=np.array([10,20,30,40,50])
print(numbers[1:4])
print(numbers[:3])
print(numbers[1:])
print(numbers[0:4:2])

[20 30 40]
[10 20 30]
[20 30 40 50]
[10 30]


In [ ]:
#Indexing in a 2D array=> contains rows and columns
#Array[row_index,column_index]
data=np.array([
    [10,20,30],
    [40,5,60],
    [70,8,90]
])
print(data[1,2])
print("=" * 50)
#Negative indexing in 2D Arrays
data=np.array([
    [10,20,30],
    [40,5,60],
    [70,8,90]
])
print(data[-1,-1])#[-1]-last row and last column

60
90


In [30]:
#Slicing a 2D Array
#Array[row_start:row_stop,column_start,column_stop]
data=np.array([
    [10,20,30],
    [40,5,60],
    [70,8,90]
])
print(data[0:2,1:3])

[[20 30]
 [ 5 60]]


In [ ]:
#Reshaping Arrays=>changing the structure of dimension of an array without changing its data
#array.reshape(roqs,columns)
numbers=np.array([1,2,3,4,5,6])
new_array=numbers.reshape(2,3)
print(new_array)


[[1 2 3]
 [4 5 6]]


In [32]:
data=np.arange(1,13)
students=data.reshape(4,3)
print(students)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#Pitfall()
#numbers=np.array([1,2,3,4,5,6])
#arr2=numbers.reshape(4,2)#ValueError: cannot reshape array of size 6 into shape (4,2)
#print(arr2)


In [35]:
#flatten()=>method converts a multi-dimensional array into a one-dimensional array
data=np.array([
    [10,20,30],
    [40,50,60]
])
result=data.flatten()
print(result)

[10 20 30 40 50 60]


In [36]:
#Transpose()=>converts rows of an array into columns and columns into rows
data=np.array([
    [11,22,33],
    [44,55,66]
])
transposed_data=data.transpose()
print(transposed_data)

[[11 44]
 [22 55]
 [33 66]]


In [39]:
#Statistical Operations
#Minimum value
#Maximum value
#Total
#Average
#iddle value
#Standard deviation
marks=np.array([85,90,72,95,88])
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())



72
95
430
86.0


In [40]:
marks=np.array([80,90,60,100,70])
print(np.median(marks))

80.0


In [43]:
#even numbers=there are two middle values
numbers=np.array([10,20,30,40])
print(np.median(numbers))

25.0
