In [5]:
#Vectorization and why Loops are slow
marks=[50,60,70,80,90]
new_marks=[]

for mark in marks:
    new_marks.append(mark+5)
print(new_marks)

[55, 65, 75, 85, 95]


In [6]:
#Using numpy vectorization
import numpy as np
marks=np.array([50,60,70,80,90])
new_marks=marks+5
print(new_marks)

[55 65 75 85 95]


In [7]:
#Multiplying Numbers
numbers=[1,2,3,4,5]
result=[]
for number in numbers:
    result.append(number*10)
print(result)

[10, 20, 30, 40, 50]


In [8]:
#using numpy vectorization
numbers=np.array([1,2,3,4,5])
result=numbers*10
print(result)

[10 20 30 40 50]


In [9]:
#Array Arithmetic
#Addition
a=np.array([10,20,30])
b=np.array([1,2,3])
result=a+b
print(result)
print("=" * 50)
#Substraction
a=np.array([100,200,300])
b=np.array([10,20,30])
result=a-b
print(result)
print("=" * 50)
#Multiplication
price=np.array([100,200,300])
print(price*4)
print("=" * 50)
#Division
numbers=np.array([10,20,30])
print(numbers/2)
print("=" * 50)
#Power
numbers=np.array([2,3,4,5])
print(numbers**2)
print("=" * 50)
#Modulus
numbers=np.array([10,11,12,13])
print(numbers%2)

[11 22 33]
[ 90 180 270]
[ 400  800 1200]
[ 5. 10. 15.]
[ 4  9 16 25]
[0 1 0 1]


In [10]:
#Brodcasting Concepts
#Scalar broadcasting
numbers=np.array([10,20,30])
print(numbers+5)


[15 25 35]


In [11]:
#giving 10% bonus
salary=np.array([20000,30000,40000])
new_salary=salary*1.10
print(new_salary)

[22000. 33000. 44000.]


In [12]:
#Broadcasting with 2D arrays
matrix=np.array([
    [10,20,30],
    [40,50,60]
])
print(matrix+10)

[[20 30 40]
 [50 60 70]]


In [13]:
matrix=np.array([
    [10,20,30],
    [40,50,60]
])
bonus=np.array([1,2,3])
result=matrix+bonus
print(result)

[[11 22 33]
 [41 52 63]]


In [14]:
#Dot Product
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.dot(a,b)
print(result)

32


In [15]:
#Shopping example
quantity=np.array([2,3,4])
price=np.array([10,20,30])
#calculate the total cost
total=np.dot(quantity,price)
print(total)

200


In [16]:
#Matrix multiplication
A=np.array([
    [1,2],
    [3,4]
])
B=np.array([
    [5,6],
    [7,8]
])
result=np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [17]:
#@=>matrix multiplication
#*=>element eise multiplication
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])

print("Element-Wise")
print(A*B)
print("=" * 50)
print("Matrix Multiplication")
print(A @ B)

Element-Wise
[[ 5 12]
 [21 32]]
Matrix Multiplication
[[19 22]
 [43 50]]


In [30]:
Marks=np.array([78,65,90,55,88,72,95,60])
print("Marks after adding Bonus:",Marks+5)
print("Average marks:",Marks.mean())
print("Highest marks:",Marks.max())
print("Lowest marks:",Marks.min())
print("Total marks:",Marks.sum())
print("marks greater than 75:",Marks[Marks>75])
print("Percentage:",(Marks/100)*100)
print("Sorted marks:",np.sort(Marks))
print("square of every mark:",Marks**2)
print(":","=" * 50)
Attendence=np.array([90,85,95,70,88,92,98,75])
print("Element-Wise")
print(Marks + Attendence)


Marks after adding Bonus: [ 83  70  95  60  93  77 100  65]
Average marks: 75.375
Highest marks: 95
Lowest marks: 55
Total marks: 603
marks greater than 75: [78 90 88 95]
Percentage: [78. 65. 90. 55. 88. 72. 95. 60.]
Sorted marks: [55 60 65 72 78 88 90 95]
square of every mark: [6084 4225 8100 3025 7744 5184 9025 3600]
: ==================================================
Element-Wise
[168 150 185 125 176 164 193 135]
