1.NumPy:Array Creation,Indexing,Slicing & Reshaping

In [1]:
import numpy as np
#printing the array
arr=np.arange(1001,1013)
print(arr)

[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012]


In [2]:
#ndim
print(arr.ndim)

1


In [3]:
#shape
print(arr.shape)

(12,)


In [4]:
#Reshape
arr=np.arange(1001,1013)
new_arr=arr.reshape(3,4)
print(new_arr)

[[1001 1002 1003 1004]
 [1005 1006 1007 1008]
 [1009 1010 1011 1012]]


In [5]:
#first row
print(new_arr[0])

[1001 1002 1003 1004]


In [6]:
#last column
print(new_arr[:,-1])

[1004 1008 1012]


In [7]:
#the first two rows
print(new_arr[0:2])

[[1001 1002 1003 1004]
 [1005 1006 1007 1008]]


In [8]:
#elements from the second row,columns 2 to 4
print(new_arr[1,1:4])

[1006 1007 1008]


In [9]:
#the last element using negative indexing
print(new_arr[-1,-1])

1012


In [10]:
#2x3 array of zeros
arr1=np.zeros((2,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
#2x3 array of ones
arr2=np.ones((2,3))
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


2.NumPy:Vectorization,Broadcasting & Dot Product

In [12]:
quantity=np.array([2,3,4])
price=np.array([100,200,150])

In [13]:
#calculating the total price for each product using vectorization
total_price=quantity+price
print(total_price)

[102 203 154]


In [14]:
#adding 10% tax to every product using broadcasting
price=np.array([100,200,150])
final_price=price*1.10
print(final_price)

[110. 220. 165.]


In [15]:
#the final price after tax
print(final_price)

[110. 220. 165.]


In [16]:
#the total bill using the dot product
total_bill=np.dot(quantity,final_price)
print(total_bill)

1540.0


In [17]:
#the discount array
discount=np.array([10,20,15])

In [18]:
#subtract the discount from the final prices
print(final_price-discount)

[100. 200. 150.]


In [19]:
#print the final amount for each product
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [20]:
#perform element-wise multiplication using *
print("Element-Wise")
print(A * B)

Element-Wise
[[ 5 12]
 [21 32]]


In [21]:
#perform matrix multiplication using @
print("Matrix Multiplication")
print(A @ B)

Matrix Multiplication
[[19 22]
 [43 50]]


3.Pandas:Employee Data Analysis

In [22]:
import pandas as pd
data = {
"Name": ["Anil", "Bhanu", "Charan", "Divya", "Esha"],
"Age": [22, 25, 21, 24, 23],
"City": ["Hyderabad", "Mumbai", "Hyderabad", "Bangalore", "Mumbai"],
"Salary": [30000, 45000, 25000, 50000, 40000]
}
df = pd.DataFrame(data)

In [23]:
#Display the complete dataframe
print(df)

     Name  Age       City  Salary
0    Anil   22  Hyderabad   30000
1   Bhanu   25     Mumbai   45000
2  Charan   21  Hyderabad   25000
3   Divya   24  Bangalore   50000
4    Esha   23     Mumbai   40000


In [24]:
#select only the name column
print(df["Name"])

0      Anil
1     Bhanu
2    Charan
3     Divya
4      Esha
Name: Name, dtype: str


In [25]:
#Select name and salary
print(df[["Name","Salary"]])

     Name  Salary
0    Anil   30000
1   Bhanu   45000
2  Charan   25000
3   Divya   50000
4    Esha   40000


In [26]:
#select the row at index 2 using loc
print(df.loc[2])

Name         Charan
Age              21
City      Hyderabad
Salary        25000
Name: 2, dtype: object


In [27]:
#Select rows 1 to 3 and columns Name and Salary using loc
print(df.loc[1:3,["Name","Salary"]])

     Name  Salary
1   Bhanu   45000
2  Charan   25000
3   Divya   50000


In [28]:
#elect rows at positions 1 to 3 and columns at positions 0 and 1 using iloc.
print(df.iloc[1:4,0:2])

     Name  Age
1   Bhanu   25
2  Charan   21
3   Divya   24


In [29]:
#find employees whose salary is greater than 30000
result=df[df["Salary"]>30000]
print(result)

    Name  Age       City  Salary
1  Bhanu   25     Mumbai   45000
3  Divya   24  Bangalore   50000
4   Esha   23     Mumbai   40000


In [30]:
#Find employees whose Age is greater than 22 AND salary is greater than 35000
result=df[
    (df["Age"]>22) &
    (df["Salary"]>35000)
]
print(result)

    Name  Age       City  Salary
1  Bhanu   25     Mumbai   45000
3  Divya   24  Bangalore   50000
4   Esha   23     Mumbai   40000


In [31]:
#Find the employess from Hyderabad OR Mumbai
result=df[
    (df["City"]== "Hyderabad") |
    (df["City"]=="Mumbai")
]
print(result)

     Name  Age       City  Salary
0    Anil   22  Hyderabad   30000
1   Bhanu   25     Mumbai   45000
2  Charan   21  Hyderabad   25000
4    Esha   23     Mumbai   40000


In [32]:
#Sort employees by salary in descending order
result=df.sort_values(by="Salary",ascending=False)
print(result)

     Name  Age       City  Salary
3   Divya   24  Bangalore   50000
1   Bhanu   25     Mumbai   45000
4    Esha   23     Mumbai   40000
0    Anil   22  Hyderabad   30000
2  Charan   21  Hyderabad   25000


In [33]:
#Rename Salary as Monthly_Salary
result=df.rename(columns={"Salary":"Monthly_Salary"})
print(result)

     Name  Age       City  Monthly_Salary
0    Anil   22  Hyderabad           30000
1   Bhanu   25     Mumbai           45000
2  Charan   21  Hyderabad           25000
3   Divya   24  Bangalore           50000
4    Esha   23     Mumbai           40000


In [34]:
#Remove the City column
result=df.drop(columns="City")
print(result)

     Name  Age  Salary
0    Anil   22   30000
1   Bhanu   25   45000
2  Charan   21   25000
3   Divya   24   50000
4    Esha   23   40000


4.Pandas:Data Cleaning & Grouping

In [35]:
import pandas as pd
data = {
"Name": ["Anil","Rahul","Priya","Sneha","Anil","Kiran",None,"Rahul"],
"Department": ["IT","HR","IT","Sales","IT","HR","Sales","HR"],
"Salary": [50000,40000,60000,None,50000,45000,55000,40000],
"Age": [25,28,24,30,25,None,26,28],
"City": ["Hyderabad","Delhi","Hyderabad","Mumbai","Hyderabad","Delhi","Mumbai","Delhi"],
"Joining_Date": ["2023-01-10","2022-05-15","2023-03-20","2021-07-12","2023-01-10","2022-08-25","2023-06-10","2022-05-15"]
}
df=pd.DataFrame(data)
print(df)


    Name Department   Salary   Age       City Joining_Date
0   Anil         IT  50000.0  25.0  Hyderabad   2023-01-10
1  Rahul         HR  40000.0  28.0      Delhi   2022-05-15
2  Priya         IT  60000.0  24.0  Hyderabad   2023-03-20
3  Sneha      Sales      NaN  30.0     Mumbai   2021-07-12
4   Anil         IT  50000.0  25.0  Hyderabad   2023-01-10
5  Kiran         HR  45000.0   NaN      Delhi   2022-08-25
6    NaN      Sales  55000.0  26.0     Mumbai   2023-06-10
7  Rahul         HR  40000.0  28.0      Delhi   2022-05-15


In [36]:
#display df.info()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Name          7 non-null      str    
 1   Department    8 non-null      str    
 2   Salary        7 non-null      float64
 3   Age           7 non-null      float64
 4   City          8 non-null      str    
 5   Joining_Date  8 non-null      str    
dtypes: float64(2), str(4)
memory usage: 516.0 bytes


In [37]:
#display df.describe()
df.describe()

,Salary,Age
count,7.000000,7.000000
mean,48571.428571,26.571429
std,7480.132415,2.149197
min,40000.000000,24.000000
25%,42500.000000,25.000000
50%,50000.000000,26.000000
75%,52500.000000,28.000000
max,60000.000000,30.000000


In [38]:
#find the number of missing values in every column
print(df.isnull().sum().sum())

3


In [39]:
#Identify missing values using isnull()
print(df.isnull())

    Name  Department  Salary    Age   City  Joining_Date
0  False       False   False  False  False         False
1  False       False   False  False  False         False
2  False       False   False  False  False         False
3  False       False    True  False  False         False
4  False       False   False  False  False         False
5  False       False   False   True  False         False
6   True       False   False  False  False         False
7  False       False   False  False  False         False


In [40]:
#Fill the missing Salary using the mean salary
mean_salary=df["Salary"].mean()
df["Salary"]=df["Salary"].fillna(mean_salary)
print(df["Salary"])


0    50000.000000
1    40000.000000
2    60000.000000
3    48571.428571
4    50000.000000
5    45000.000000
6    55000.000000
7    40000.000000
Name: Salary, dtype: float64


In [41]:
#Fill the missing Age using the median age
median_age=df["Age"].median()
df["Age"]=df["Age"].fillna(median_age)
print(df["Age"])

0    25.0
1    28.0
2    24.0
3    30.0
4    25.0
5    26.0
6    26.0
7    28.0
Name: Age, dtype: float64


In [42]:
#If the City column contained a missing value, explain which strategy you would use for a categoricaln column
mode_city=df["City"].mode()[0]
df["City"]=df["City"].fillna(mode_city)
print(df["City"])

0    Hyderabad
1        Delhi
2    Hyderabad
3       Mumbai
4    Hyderabad
5        Delhi
6       Mumbai
7        Delhi
Name: City, dtype: str


In [43]:
#Find the number of employees in each department using value_counts()
print(df.value_counts("Department"))

Department
IT       3
HR       3
Sales    2
Name: count, dtype: int64


In [44]:
# Find the unique departments using unique().
print(df["Department"].unique())

<StringArray>
['IT', 'HR', 'Sales']
Length: 3, dtype: str


In [45]:
#Find the number of unique departments using nunique().
print(df["Department"].nunique())

3


In [46]:
# Identify duplicate rows using duplicated()
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
dtype: bool


In [47]:
#Find the average salary for each department
print(df.groupby("Department")["Salary"].mean())


Department
HR       41666.666667
IT       53333.333333
Sales    51785.714286
Name: Salary, dtype: float64


In [48]:
#Find the total salary for each department.
print(df.groupby("Department")["Salary"].sum())

Department
HR       125000.000000
IT       160000.000000
Sales    103571.428571
Name: Salary, dtype: float64


In [49]:
#Find the maximum and minimum salary for each department.
result=df.groupby("Department")["Salary"].agg(
    ["max","min"]
)
print(result)
      

                max           min
Department                       
HR          45000.0  40000.000000
IT          60000.0  50000.000000
Sales       55000.0  48571.428571


In [50]:
#Calculate sum, mean, max, and min together using agg().
result=df.groupby("Department")["Salary"].agg(
    ["sum","mean","max","min"]
)
print(result)

                      sum          mean      max           min
Department                                                    
HR          125000.000000  41666.666667  45000.0  40000.000000
IT          160000.000000  53333.333333  60000.0  50000.000000
Sales       103571.428571  51785.714286  55000.0  48571.428571
