In [1]:
#v->2i+3j
#u->4i+5J
#scalar = size only=5
#vector = size + direction=[3,4]
#magnitude = size/length[5]

In [2]:
import numpy as np
u=np.array([1,2,3])
v=np.array([4,5,6])
print("u+v",u+v) #element-wise addition

u+v [5 7 9]


In [3]:
print("u-v",u-v)#element wise substraction

u-v [-3 -3 -3]


In [4]:
k=6
print("k*u =",k*u)

k*u = [ 6 12 18]


In [5]:
print("Magnitude of u =",np.linalg.norm(u))

Magnitude of u = 3.7416573867739413


In [6]:
#unit vector=>a vector whose magnitude is 1
k=np.linalg.norm(u)
unit_vector_u=u/k
print(np.linalg.norm(unit_vector_u))

1.0


In [7]:
#Matrix
#A=[[1 2]
#   [3 4]]
#shape of a matrix=>2x2=>no.of rows x no.of columns

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print(A)
print(A.shape)
print(B)
print(B.shape)

[[1 2]
 [3 4]]
(2, 2)
[[5 6]
 [7 8]]
(2, 2)


In [8]:
print("A+B=",A+B)
print("A-B=",A-B)


A+B= [[ 6  8]
 [10 12]]
A-B= [[-4 -4]
 [-4 -4]]


In [9]:
k=3
print(A)
print(k*A)

[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]


In [10]:
#A=>mxn
#B=>pxq
#if we multiply two ,matrices A and B=>they must be shpe of u*v and v*u i.e number of columns in matrix A must be equal to number of rows in matrix B=>the output matrix will now be having the dimensions of u*w

In [11]:
#A=>mxn
#B=>pxq

#if A and B are of above mentioned dimensions..if we want A x B to be happening then 'n' must be equal to 'p'

In [12]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6,9],[7,8,10]])

print(A.shape)
print(B.shape)

(2, 2)
(2, 3)


In [13]:
C=A@B
print(C.shape)
print(C)

(2, 3)
[[19 22 29]
 [43 50 67]]


In [14]:
#Transpose=>rows and columns are flipped
A= np.array([[1,2],[3,4]])
B = np.array([[5,6,9],[7,8,10]])

print(A)
print("Transpose of A:",A.T)

print(B)
print("Transpose of B:",B.T)

[[1 2]
 [3 4]]
Transpose of A: [[1 3]
 [2 4]]
[[ 5  6  9]
 [ 7  8 10]]
Transpose of B: [[ 5  7]
 [ 6  8]
 [ 9 10]]


In [15]:
C=B.T
print(C)

[[ 5  7]
 [ 6  8]
 [ 9 10]]


In [16]:
print(C@A)

[[26 38]
 [30 44]
 [39 58]]
