In [1]:
import numpy as np
import matplotlib.pyplot as plt

# learning rate -> rate at which the algorithm learns
# epochs -> number of times we learn

#Dataset
X=np.array([1,2,3,4,5],dtype=float)
y=np.array([22,32,42,52,62])
#y=10*x+12


#initialize parameters
#y=mx+c
#y=wx+b
w=0.0
b=0.0

#hyperparameters
learning_rate=0.05
epochs=1000

n=len(X)
loss_history=[]

#gradient descent
for i in range(epochs):
# we start making predictions with existing parameters that we have and then evaluate ourself and improvise
    y_pred=w*X+b
    print(w,b)
    print(y_pred)
    loss=np.mean((y_pred-y)**2) #MSE
    loss_history.append(loss)
    print(loss)

    # now once we are done calculating the loss, now we need improvise parameters.
    dw=(2/n)*np.mean((y_pred-y)*X)
    db=(2/n)*np.mean((y_pred-y)*1)

    # parameter_new = parameter_old - lr*change
    # w_new = w_old -lr*dw
    # b_new=b_old-lr*db
    
    w=w-learning_rate*dw
    b=b-learning_rate*db


0.0 0.0
[0. 0. 0. 0. 0.]
1964.0
2.9200000000000004 0.8400000000000001
[ 3.76  6.68  9.6  12.52 15.44]
1150.0128
5.1472 1.4880000000000002
[ 6.6352 11.7824 16.9296 22.0768 27.224 ]
675.6242918400001
6.845536 1.989408
[ 8.834944 15.68048  22.526016 29.371552 36.217088]
399.137339086848
8.1401536 2.37888768
[10.51904128 18.65919488 26.79934848 34.93950208 43.07965568]
237.97786389566426
9.1265865472 2.6829007104
[11.80948726 20.9360738  30.06266035 39.1892469  48.31583345]
144.02577999077678
9.877763464192 2.92164750336
[12.79941097 22.67717443 32.5549379  42.43270136 52.31046482]
89.23908169099856
10.449356651868161 3.11054874544128
[13.5599054  24.00926205 34.4586187  44.90797535 55.357332  ]
57.27627469737304
10.883865263730689 3.2613763714203645
[14.14524164 25.0291069  35.91297216 46.79683743 57.68070269]
38.61434350199064
11.213732323424715 3.383116928168116
[14.59684925 25.81058158 37.0243139  48.23804622 59.45177855]
27.703744487086784
11.463724196581191 3.4826306501992708
[14.946

In [2]:
#22,32,42,52,62
#y = 10*x +12


#w=0
#b=0
#loss =1964


#after 1000 epochs with lr=0.05
#w=10.08
#b=11.7
#loss=0.015

In [3]:
import numpy as np
import matplotlib.pyplot as plt

# learning rate -> rate at which the algorithm learns
# epochs -> number of times we learn

# Dataset

X = np.array([1,2,3,4,5],dtype=float)
y=np.array([22,32,42,52,62])
# y = 10*x +12


# initialize paramaters
# y =mx+c
# y=wx+b
w=0.0
b=0.0

# hyperparameters
learning_rate=0.5
epochs=10

n=len(X)
loss_history=[]

# gradient descent
for i in range(epochs):
  # we start making predictions with existing parameters that we have and then evaluate ourself and improvise
  y_pred = w*X+b
  print(w,b)
  print(y_pred)
  loss = np.mean((y_pred-y)**2)  #MSE
  loss_history.append(loss)
  print(loss)

  # now once we are done calculating the loss, now we need improvise parameters.

  dw = (2/n) * np.mean((y_pred-y)*X)
  db = (2/n) * np.mean((y_pred-y)*1)

  # parameter_new = parameter_old - lr*change
  # w_new = w_old -lr*dw
  # b_new=b_old-lr*db
  w= w- learning_rate*dw
  b = b- learning_rate* db




0.0 0.0
[0. 0. 0. 0. 0.]
1964.0
29.200000000000003 8.4
[ 37.6  66.8  96.  125.2 154.4]
3653.280000000001
-10.88000000000001 -2.400000000000004
[-13.28 -24.16 -35.04 -45.92 -56.8 ]
6807.110400000005
43.69600000000001 13.008000000000004
[ 56.704 100.4   144.096 187.792 231.488]
12694.434048000012
-31.04000000000002 -7.411200000000006
[ -38.4512  -69.4912 -100.5312 -131.5712 -162.6112]
23683.706173440023
70.89472000000004 21.09504000000001
[ 91.98976 162.88448 233.7792  304.67392 375.56864]
44195.59540039686
-68.53068800000008 -17.26080000000001
[ -85.791488 -154.322176 -222.852864 -291.383552 -359.91424 ]
82481.17748450935
121.79330560000011 35.70977280000005
[157.5030784 279.296384  401.0896896 522.8829952 644.6763008]
153940.8915309747
-138.37783040000022 -36.10816512000004
[-174.48599552 -312.86382592 -451.24165632 -589.61948672 -727.99731712]
287319.2926377201
216.91829555200042 62.54016614400011
[ 279.4584617   496.37675725  713.2950528   930.21334835 1147.1316439 ]
536267.409982046